name: Build and deploy site

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v2
    - name: Install node 14
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install deps
      run: npm install
    - name: Build using Rollup
      run: npm run build
    - name: Copy site dir to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks
      env:
        AWS_S3_BUCKET: zenmumbler.net
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: site
        DEST_DIR: dtbb
    - name: Purge Cloudflare cache
      uses: jakejarvis/cloudflare-purge-action@master
      env:
        CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
        CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_PURGE_TOKEN }}
        PURGE_URLS: '["https://zenmumbler.net/dtbb/dtbb.css","https://zenmumbler.net/dtbb/dtbb.js","https://zenmumbler.net/dtbb/index.html","https://zenmumbler.net/dtbb/task_indexer.js","https://zenmumbler.net/dtbb/data/manifest.json"]'
